#!/bin/bash

display_info() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print}')
        record_type=$(echo "$result" | awk '{print $2}')
        destination=$(echo "$result" | awk '{print $NF}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

if [ $# -eq 1 ]; then
    domain=$1
    display_info "$domain"
elif [ $# -eq 2 ]; then
    domain=$1
    subdomain=$2
    display_info "$domain" "$subdomain"
else
    echo "Invalid number of arguments. Usage: $0 domain [subdomain]"
fi
