#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Add rewrite rule and custom error page to Nginx configuration
sed -i '/server_name _;/a \\\trewrite ^\/redirect_me https:\/\/github.com\/Tolulope05 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Add custom header to Nginx configuration
sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/a \\\tadd_header X-Served-By \"$HOSTNAME\";' /etc/nginx/nginx.conf

# Start Nginx service
service nginx start
