#!/usr/bin/env bash

# Script that configures Nginx server with a custom header

apt-get -y update
apt-get -y install nginx

# Configure custom HTTP response header
echo 'add_header X-Served-By $hostname;' | tee /etc/nginx/conf.d/custom-header.conf

# Restart Nginx service
systemctl restart nginx
