#!/usr/bin/env bash

# Update the system packages
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Configure Nginx
sudo sed -i '/^http {/a \        server_tokens off;\n        location / {\n            add_header X-Served-By $hostname;\n        }' /etc/nginx/nginx.conf

# Restart Nginx
sudo systemctl restart nginx
