#!/usr/bin/env bash

# Update the system packages
sudo apt update

# Install HAproxy
sudo apt install -y haproxy

# Configure HAproxy
sudo sed -i 's/^frontend.*$/frontend http_frontend\n    bind *:80\n    default_backend http_backend/' /etc/haproxy/haproxy.cfg
sudo sed -i '/^backend http_backend/a \    balance roundrobin\n    server web-01 [STUDENT_ID]-web-01:80 check\n    server web-02 [STUDENT_ID]-web-02:80 check' /etc/haproxy/haproxy.cfg

# Enable HAproxy service
sudo sed -i '/ENABLED=/c ENABLED=1' /etc/default/haproxy

# Restart HAproxy
sudo systemctl restart haproxy
